name: real_estate
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  cached_network_image: ^3.1.0
  intl: ^0.19.0
  flutter_riverpod: ^2.4.9
  build_runner: ^2.3.3
  google_sign_in: ^6.2.1


flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/house.jpg
    - images/whoa-1.png
    - images/new-beginnings-1-bg.png
    - images/search-1.png
    - images/reflecting-1.png
    - images/search-1-js2.png
    - images/home.png
    - images/logo2.png
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-hdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
    - images/email.png
    - images/capybara.png
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
